apiVersion: v1
kind: ServiceAccount
metadata:
  name: milvus-k8s-server
  namespace: milvus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvus-k8s-server
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: milvus-k8s-server
  namespace: milvus
subjects:
  - kind: ServiceAccount
    name: milvus-k8s-server
    namespace: milvus
roleRef:
  kind: ClusterRole
  name: milvus-k8s-server
  apiGroup: rbac.authorization.k8s.io
