apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: milvus-k8s-server
  namespace: milvus
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
