kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: milvus-k8s-server
  namespace: milvus
subjects:
  - kind: ServiceAccount
    name: milvus-k8s-server
    namespace: milvus
roleRef:
  kind: Role
  name: milvus-k8s-server
  apiGroup: rbac.authorization.k8s.io

