apiVersion: v1
kind: Service
metadata:
  labels:
    app: milvus-k8s-server
  name: milvus-k8s-server
  namespace: milvus
spec:
  ports:
    - name: server
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: milvus-k8s-server
  type: ClusterIP